### ISSUE TITLE
Launch4j build fails if outfile parent directories do not exist

### ISSUE THREAD

**Issue by matthewhorridge** [lukaszlenart/launch4j-maven-plugin#37]
If the parent directories of the outfile do not exist before the plugin execution then the build will fail.

**Comment by lukaszlenart** [comment]
Is there any stacktrace? Plugin just passes configuration to Launch4j library.

**Comment by matthewhorridge** [comment]
Yes, here it is.  The key message is in the INFO message that comes before the ERROR (the ERROR itself doesn't seem so helpful).  If I manually create the parent directories (in this case 'otherdir') then things work as expected.

```java
[INFO] launch4j: /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/bin/ld: cannot open output file /Users/matthewhorridge/IdeaProjects/protege-github/protege-desktop/target/otherdir/Protégé.exe: No such file or directory
[ERROR] 
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/bin/ld -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem console -s /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/crt2.o /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/head/consolehead.o /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/head/head.o /var/folders/dk/2w_xk5vn6955mzq63gsmngnm0000gp/T/launch4j5589145922423802685o /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libmingw32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libgcc.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libmsvcrt.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libkernel32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libuser32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libadvapi32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libshell32.a -o /Users/matthewhorridge/IdeaProjects/protege-github/protege-desktop/target/otherdir/Protégé.exe
	at net.sf.launch4j.Builder.build(Builder.java:146)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:358)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: net.sf.launch4j.ExecException: Exec failed (1): /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/bin/ld -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem console -s /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/crt2.o /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/head/consolehead.o /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/head/head.o /var/folders/dk/2w_xk5vn6955mzq63gsmngnm0000gp/T/launch4j5589145922423802685o /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libmingw32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libgcc.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libmsvcrt.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libkernel32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libuser32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libadvapi32.a /Users/matthewhorridge/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-mac/w32api/libshell32.a -o /Users/matthewhorridge/IdeaProjects/protege-github/protege-desktop/target/otherdir/Protégé.exe
	at net.sf.launch4j.Util.exec(Util.java:156)
	at net.sf.launch4j.Cmd.exec(Builder.java:212)
	at net.sf.launch4j.Builder.build(Builder.java:114)
	... 22 more
```

**Comment by lukaszlenart** [comment]
It has nothing to do with the plugin, those messages are generate by Launch4j library, please report the issue [here](http://launch4j.sourceforge.net/).

You can also use `maven-antrun-plugin` to create all the parent directories http://stackoverflow.com/questions/4085973/create-directory-when-needed-in-maven

**Comment by matthewhorridge** [comment]
> It has nothing to do with the plugin, those messages are generate by Launch4j library, please report the issue here.

o.k. will do.  I did wonder about this, but it wasn't clear to me whether launch4j expects the directory to already exist or not.

> You can also use maven-antrun-plugin to create all the parent directories

I'm already doing that :)  It just seems ugly though.  Only a temporary fix I hope.  

Thanks for looking into this.
