### ISSUE TITLE
Application jar doesn't exist.

### ISSUE THREAD

**Issue by amedee** [lukaszlenart/launch4j-maven-plugin#39]
Stack trace:

```
[ERROR] 
net.sf.launch4j.BuilderException: Application jar doesn't exist.
        at net.sf.launch4j.Builder.build(Builder.java:76)
        at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:358)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

pom snippet:

```
	<profiles>
		<profile>
			<id>exe</id>
			<build>
				<plugins>
					<plugin>
						<!-- see http://alakai.org/reference/plugins/launch4j-plugin-usage.html -->
						<!-- see http://launch4j.sourceforge.net/docs.html for more config options -->
						<groupId>com.akathist.maven.plugins.launch4j</groupId>
						<artifactId>launch4j-maven-plugin</artifactId>
						<version>1.7.10</version>
						<executions>
							<execution>
								<id>launch4j</id>
								<phase>package</phase>
								<goals>
									<goal>launch4j</goal>
								</goals>
								<configuration>
									<dontWrapJar>false</dontWrapJar>
									<headerType>gui</headerType>
									<outfile>target/Rups.exe</outfile>
									<jar>target/itext-rups-${project.version}-jar-with-dependencies.jar</jar>
									<errTitle>Rups</errTitle>
									<icon>config/logo.ico</icon>
									<classPath>
										<mainClass>com.itextpdf.rups.RupsLauncher</mainClass>
										<addDependencies>true</addDependencies>
										<preCp>anything</preCp>
									</classPath>
									<jre>
										<minVersion>1.5.0</minVersion>
									</jre>
									<versionInfo>
										<fileVersion>7.0.0</fileVersion>
										<txtFileVersion>${project.version}</txtFileVersion>
										<fileDescription>Rups, object view of pdf content</fileDescription>
										<copyright>AGPL</copyright>
										<productVersion>7.0.0</productVersion>
										<txtProductVersion>${project.version}</txtProductVersion>
										<productName>Rups</productName>
										<internalName>itext-rups</internalName>
										<originalFilename>Rups.exe</originalFilename>
									</versionInfo>
									<!-- <splash> <file>${basedir}/src/main/installer/images/splash.bmp</file>
										<waitForWindow>true</waitForWindow> <timeout>60</timeout> <timeoutErr>false</timeoutErr>
										</splash> -->
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

I got the same error with `org.bluestemsoftware.open.maven.plugin:launch4j-plugin:1.5.0.0:launch4j`. What is the relation between `launch4j-plugin` and `launch4j-maven-plugin`?

**Comment by lukaszlenart** [comment]
How do you create `<jar>target/itext-rups-${project.version}-jar-with-dependencies.jar</jar>`?

> What is the relation between `launch4j-plugin` and `launch4j-maven-plugin`?

No relation, just another plugin

**Comment by amedee** [comment]
I just run `mvn clean install` and that jar is in the `target` directory. The only difference is that `${project.version}` is substituted with the value inside `<version></version>`.

**Comment by amedee** [comment]
Yeahhhh never mind, PEBKAC. I ran `mvn -e -X`, copy/pasted the value of jar after `ls` and `file`, and they didn't find it. The `finalName` was slightly modified in the parent POM.
