### ISSUE TITLE
Support for 64bit

### ISSUE THREAD

**Issue by jschneider** [lukaszlenart/launch4j-maven-plugin#4]
While I really love the plugin, I run into problems when trying to use this plugin on 64bit Ubuntu:

```
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/var/lib/jenkins/jobs/com.cedarsoft.deger/workspace/.repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.5.1/launch4j-maven-plugin-1.5.1-workdir-linux/bin/windres": error=2, No such file or directory
    at net.sf.launch4j.Builder.build(Builder.java:144)
    at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:353)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/var/lib/jenkins/jobs/com.cedarsoft.deger/workspace/.repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.5.1/launch4j-maven-plugin-1.5.1-workdir-linux/bin/windres": error=2, No such file or directory
    at net.sf.launch4j.Util.exec(Util.java:152)
    at net.sf.launch4j.Cmd.exec(Builder.java:205)
    at net.sf.launch4j.Builder.build(Builder.java:97)
    ... 22 more
Caused by: java.io.IOException: Cannot run program "/var/lib/jenkins/jobs/com.cedarsoft.deger/workspace/.repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.5.1/launch4j-maven-plugin-1.5.1-workdir-linux/bin/windres": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
    at java.lang.Runtime.exec(Runtime.java:617)
    at java.lang.Runtime.exec(Runtime.java:485)
    at net.sf.launch4j.Util.exec(Util.java:117)
    ... 24 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
    ... 27 more
```

**Comment by ooxi** [comment]
Is there a workaround available? I'm constantly hitting this bug :(

I know you are not the not the author of launch4j but of the maven plugin but maybe you know a solution.

**Comment by lukaszlenart** [comment]
@ooxi just install above the mentioned libs - that's the solution

**Comment by ooxi** [comment]
Thanks!

**Comment by nbauma109** [comment]
Please give an update of the package list to install. The library name pattern with "32" in it is an old pattern that is not supported anymore. But even after renaming and adding support for i386, I'm still getting the issue:

        sudo dpkg --add-architecture i386
        sudo apt-get -y update
        sudo apt-get -y install libz1:i386 libncurses5:i386 libbz2-1.0:i386

Cannot run program "/root/.m2/repository/net/sf/launch4j/launch4j/3.14/launch4j-3.14-workdir-linux64/bin/windres": error=2, No such file or directory -> [Help 1]

Before that it says:

[INFO] [INFO] launch4j: Compiling resources
[INFO] [INFO] launch4j: Generated resource file...

Normal execution path is:

[INFO] [INFO] launch4j: Compiling resources
[INFO] [INFO] launch4j: Linking
[INFO] [INFO] launch4j: Wrapping

**Comment by Weylend** [comment]
How to make it work on Debian 11?

```
apt-get -y install libz1:i386 libncurses5:i386 libbz2-1.0:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'zlib1g:i386' instead of 'libz1:i386'
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 lib32z1 : Depends: libc6-i386 (>= 2.4) but it is not going to be installed
 libbz2-1.0:i386 : Depends: libc6:i386 (>= 2.4) but it is not going to be installed
 libncurses5:i386 : Depends: libtinfo5:i386 (= 6.2+20201114-2) but it is not going to be installed
                    Depends: libc6:i386 (>= 2.7) but it is not going to be installed
 zlib1g : Breaks: zlib1g:i386 (!= 1:1.2.11.dfsg-2) but 1:1.2.11.dfsg-2+deb11u1 is to be installed
 zlib1g:i386 : Depends: libc6:i386 (>= 2.4) but it is not going to be installed
               Breaks: zlib1g (!= 1:1.2.11.dfsg-2+deb11u1) but 1:1.2.11.dfsg-2 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

```

**Comment by lukaszlenart** [comment]
Did you try to install MinGW-w64?
https://www.mingw-w64.org/downloads/#debian
