### ISSUE TITLE
Launch4j fails on SLES

### ISSUE THREAD

**Issue by bjking2** [lukaszlenart/launch4j-maven-plugin#51]
The maven build runs without issues on my windows laptop.

On our build server (SLES) I get the following error:

[ERROR] 
```
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/global/apps/cdbuilt/build_server/maven/connecteddrive/local-repo-maven-3/net/sf/launch4j/launch4j/3.9/launch4j-3.9-workdir-linux/bin/windres": error=2, No such file or directory
	at net.sf.launch4j.Builder.build(Builder.java:149)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:402)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/global/apps/cdbuilt/build_server/maven/connecteddrive/local-repo-maven-3/net/sf/launch4j/launch4j/3.9/launch4j-3.9-workdir-linux/bin/windres": error=2, No such file or directory
	at net.sf.launch4j.Util.exec(Util.java:160)
	at net.sf.launch4j.Cmd.exec(Builder.java:215)
	at net.sf.launch4j.Builder.build(Builder.java:100)
	... 22 more
Caused by: java.io.IOException: Cannot run program "/global/apps/cdbuilt/build_server/maven/connecteddrive/local-repo-maven-3/net/sf/launch4j/launch4j/3.9/launch4j-3.9-workdir-linux/bin/windres": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at net.sf.launch4j.Util.exec(Util.java:128)
	... 24 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 27 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.998 s
[INFO] Finished at: 2017-01-07T20:37:54+01:00
[INFO] Final Memory: 76M/661M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15:launch4j (launch4j) on project pom-root: Failed to build the executable; please verify your configuration. net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/global/apps/cdbuilt/build_server/maven/connecteddrive/local-repo-maven-3/net/sf/launch4j/launch4j/3.9/launch4j-3.9-workdir-linux/bin/windres": error=2, No such file or directory -> [Help 1]
```

**Comment by bjking2** [comment]
I am using the following plugin configuration:

<plugin>
				<groupId>com.akathist.maven.plugins.launch4j</groupId>
    			<artifactId>launch4j-maven-plugin</artifactId>
    			<version>1.7.15</version>
				<executions>
					<execution>
						<id>launch4j</id>
						<phase>package</phase>
						<goals>
							<goal>launch4j</goal>
						</goals>
						<configuration>
							<headerType>gui</headerType>
							<dontWrapJar>false</dontWrapJar>
							<jar>${project.build.directory}/MSMonitor-${project.version}-launcher.jar</jar>
							<outfile>${project.build.directory}/MSMonitor.exe</outfile>
							<errTitle>XXX</errTitle>
							<chdir>.</chdir>
							<stayAlive>false</stayAlive>
							<jre>
								<minVersion>1.8.0</minVersion>
							</jre>
							<versionInfo>
								<fileVersion>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}.0</fileVersion>
								<txtFileVersion>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}.0</txtFileVersion>
								<productVersion>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}.0</productVersion>
								<txtProductVersion>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}.0</txtProductVersion>
								<fileDescription>Cross-platform Java application wrapper</fileDescription>
								<copyright>XXX</copyright>
								<productName>MSMonitor</productName>
								<companyName>XXXX</companyName>
								<internalName>Microservice Monitor</internalName>
								<originalFilename>MSMonitor.exe</originalFilename>
							</versionInfo>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by lukaszlenart** [comment]
Is it a 64bi SLES? If yes, did you install are required libs? https://github.com/lukaszlenart/launch4j-maven-plugin#faq

**Comment by bjking2** [comment]
Yes, it is a 64 bit SLES. I will check if the libraries are available. Thanks.

**Comment by kristian** [comment]
Same goes when trying to execute the launch4j goal on Travis, see: https://travis-ci.org/kristian/JDigitalSimulator

Recommended libs have been installed:

```
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6:i386 libstdc++6:i386
```

It says 'No such file or directory', any idea why this is happening? Thanks.

**Comment by lukaszlenart** [comment]
It supposed to be `686` not `386`

**Comment by kristian** [comment]
Success! The following command did it for me on Travis (Ubuntu 64bit Linux)

```
- sudo apt-get update -qq
- sudo apt-get install -qq lib32z1 lib32ncurses5 lib32bz2-1.0 zlib1g:i386
```

**Comment by lukaszlenart** [comment]
As in [FAQ](https://github.com/lukaszlenart/launch4j-maven-plugin#faq) ;-)

**Comment by kristian** [comment]
Yes, like in the FAQ, but zlib.i686, ncurses-libs.i686 and bzip2-libs.i686 seem to be not available on Ubuntu, so I chose zlib1g:i386. I hope this fixes the problem of the original reporter as well (he tried in on SLES Linux instead).
