### ISSUE TITLE
noob question about including dependancies

### ISSUE THREAD

**Issue by darthShana** [lukaszlenart/launch4j-maven-plugin#64]
HI..
Im hoping you could help me with using your plugin to bundle up my application as a executable
[project pom file](https://github.com/darthShana/lostVictoriesLauncher/blob/master/pom.xml)

I a mvn clean package which generates to exe
However when i try the executable i get
darthShana@DESKTOP-676LN36 MINGW64 /c/development/jmeProjects/lostVictoriesLauncher (master)
$ Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/codec/DecoderException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.DecoderException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

However the above class is included in my dependencies.. Could you let me know if there is something obvious im doing wrong.. I excluded maven-assembly-plugin becuase it seemed to do with putting the exe in a zip which i don't need..

**Comment by lukaszlenart** [comment]
But do you distribute all the jars with your exe? This is was the maven-assembly-plugin does.

**Comment by darthShana** [comment]
ah ha.. thanks so if i wanted create a exe with all my dependencies but didnt want anything ziped should i do something like

`<plugin>
  <artifactId>maven-assembly-plugin</artifactId>
  <configuration>
    <archive>
      <manifest>
        <mainClass>fully.qualified.MainClass</mainClass>
      </manifest>
    </archive>
    <descriptorRefs>
      <descriptorRef>jar-with-dependencies</descriptorRef>
    </descriptorRefs>
  </configuration>
  <executions>
    <execution>
      <id>make-assembly</id> 
      <phase>package</phase> 
      <goals>
        <goal>single</goal>
      </goals>
    </execution>
  </executions>
</plugin>`

is that the right phase? and should it go before the launch4j plugin?

**Comment by lukaszlenart** [comment]
You have two options:
- create an uber jar which is a jar containing all the classes, and then you wrap the jar with exe
- pack all the jars with zip plus your exe

**Comment by lukaszlenart** [comment]
And yes and yes :)

**Comment by darthShana** [comment]
thanks for you work! and fast response...
