### ISSUE TITLE
Failed to execute goal ... Free form file version exceeds the maximum length of 50 characters.

### ISSUE THREAD

**Issue by ryanthara** [lukaszlenart/launch4j-maven-plugin#68]
I try to build RyCON with my maven configuration and runs in this 32bit error on macOS High Sierra.

Is there anybody out there, who can help me to solve this error?

```
[DEBUG] OS = Mac OS X
[DEBUG] Architecture = x86_64
[DEBUG] Found launch4j version 3.11
[INFO] Platform-specific work directory already exists: /Users/sebastian/.m2/repository/net/sf/launch4j/launch4j/3.11/launch4j-3.11-workdir-mac
[DEBUG] headerType = gui
[DEBUG] outfile = /Users/sebastian/Coder/github/RyCON/RyCON_Win64/target/RyCON_Windows64.exe
[DEBUG] jar = target/RyCON_Windows64.jar
[DEBUG] dontWrapJar = false
[DEBUG] errTitle = RyCON
[DEBUG] downloadUrl = http://java.com/download
[DEBUG] supportUrl = null
[DEBUG] cmdLine = null
[DEBUG] chdir = null
[DEBUG] priority = normal
[DEBUG] stayAlive = false
[DEBUG] restartOnCrash = false
[DEBUG] icon = /Users/sebastian/Coder/github/RyCON/RyCON_Win64/src/main/app-resources/RyCON.ico
[DEBUG] objs = [w32api/crt2.o, head/guihead.o, head/head.o]
[DEBUG] libs = [w32api/libmingw32.a, w32api/libgcc.a, w32api/libmsvcrt.a, w32api/libkernel32.a, w32api/libuser32.a, w32api/libadvapi32.a, w32api/libshell32.a]
[DEBUG] vars = null
[DEBUG] singleInstance = null
[DEBUG] jre.path = null
[DEBUG] jre.minVersion = 1.7.0
[DEBUG] jre.maxVersion = null
[DEBUG] jre.jdkPreference = preferJre
[DEBUG] jre.initialHeapSize = null
[DEBUG] jre.initialHeapPercent = null
[DEBUG] jre.maxHeapSize = 512
[DEBUG] jre.maxHeapPercent = null
[DEBUG] jre.opts = null
[DEBUG] classPath.mainClass = de.ryanthara.ja.rycon.ui.MainApplication
[DEBUG] classPath.addDependencies = true
[DEBUG] classPath.jarLocation = 
[DEBUG] classPath.preCp = null
[DEBUG] classPath.postCp = null
[DEBUG] splash = null
[DEBUG] versionInfo.fileVersion = 2.0.255.0
[DEBUG] versionInfo.txtFileVersion = 2.0.0-SNAPSHOT 255
                                            2018-01-02 13:03:51
[DEBUG] versionInfo.fileDescription = RyCON converts, clean, process and process measurement files
                                            and coordinate data for surveyors
[DEBUG] versionInfo.copyright = Sebastian Aust
[DEBUG] versionInfo.productVersion = 2.0.255.0
[DEBUG] versionInfo.txtProductVersion = 2.0.0-SNAPSHOT 255
                                            2018-01-02 13:03:51
[DEBUG] versionInfo.productName = RyCON
[DEBUG] versionInfo.companyName = null
[DEBUG] versionInfo.internalName = RyCON for Windows as 64 Bit Executable
[DEBUG] versionInfo.originalFilename = RyCON_Windows64.exe
[DEBUG] versionInfo.language = !Language.english.us!
[DEBUG] versionInfo.languageIndex = 15
[DEBUG] versionInfo.trademarks = null
[DEBUG] messages = null
[ERROR] 
net.sf.launch4j.BuilderException: Free form file version exceeds the maximum length of 50 characters.
	at net.sf.launch4j.Builder.build(Builder.java:76)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:403)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

and a little bit later I got this

```
[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.21:launch4j (default) on project RyCON_Win64: Failed to build the executable; please verify your configuration. Free form file version exceeds the maximum length of 50 characters. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.21:launch4j (default) on project RyCON_Win64: Failed to build the executable; please verify your configuration.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to build the executable; please verify your configuration.
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:406)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: net.sf.launch4j.BuilderException: Free form file version exceeds the maximum length of 50 characters.
	at net.sf.launch4j.Builder.build(Builder.java:76)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:403)
	... 23 more
[ERROR]
```

My pom looks like this

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- coordinates -->
    <artifactId>RyCON_Win32</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>RyCON for Windows (32-bit)</name>

    <!-- inherit all the things which are global for RyCON -->
    <parent>
        <groupId>de.ryanthara.ja.rycon</groupId>
        <artifactId>rycon-build</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../rycon-build/pom.xml</relativePath>
    </parent>

    <!-- build management -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <finalName>RyCON_Windows32</finalName>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Specification-Title>${project.name}</Specification-Title>
                                        <Specification-Version>${project.version}-${maven.build.number}
                                        </Specification-Version>
                                        <Specification-Vendor>Sebastian Aust</Specification-Vendor>
                                        <Implementation-Version>${maven.build.timestamp}</Implementation-Version>
                                        <Implementation-Vendor>Windows32</Implementation-Vendor>
                                        <Main-Class>de.ryanthara.ja.rycon.ui.MainApplication</Main-Class>
                                        <SplashScreen-Image>de/ryanthara/ja/rycon/gui/RyCON.png</SplashScreen-Image>
                                        <Codebase>https://code.ryanthara.de/RyCON</Codebase>
                                        <Application-Name>RyCON</Application-Name>
                                    </manifestEntries>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.txt</exclude>
                                        <exclude>META-INF/LICENSE*</exclude>
                                        <exclude>META-INF/NOTICE*</exclude>
                                        <exclude>META-INF/maven/</exclude>
                                        <exclude>external.xpt</exclude>
                                        <exclude>version.txt</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <!-- Use a profile for the launch4j-plugin to build the exe of RyCON -->
    <profiles>
        <profile>
            <id>rycon</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>parse-version</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>com.akathist.maven.plugins.launch4j</groupId>
                        <artifactId>launch4j-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>launch4j</goal>
                                </goals>
                                <configuration>
                                    <headerType>gui</headerType>
                                    <outfile>target/RyCON_Windows32.exe</outfile>
                                    <jar>target/RyCON_Windows32.jar</jar>
                                    <errTitle>RyCON</errTitle>
                                    <icon>src/main/app-resources/RyCON.ico</icon>
                                    <classPath>
                                        <mainClass>de.ryanthara.ja.rycon.ui.MainApplication</mainClass>
                                    </classPath>
                                    <jre>
                                        <minVersion>1.7.0</minVersion>
                                        <maxHeapSize>512</maxHeapSize>
                                    </jre>
                                    <versionInfo>
                                        <fileVersion>
                                            ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${maven.build.number}.0
                                        </fileVersion>
                                        <txtFileVersion>${project.version} ${maven.build.number} ${maven.build.timestamp}
                                        </txtFileVersion>
                                        <fileDescription>RyCON converts, clean, process and process measurement files and coordinate data for surveyors
                                        </fileDescription>
                                        <copyright>Sebastian Aust</copyright>
                                        <productName>RyCON</productName>
                                        <productVersion>
                                            ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${maven.build.number}.0
                                        </productVersion>
                                        <txtProductVersion>${project.version} ${maven.build.number} ${maven.build.timestamp}
                                        </txtProductVersion>
                                        <internalName>RyCON for Windows as 32 Bit Executable</internalName>
                                        <originalFilename>RyCON_Windows32.exe</originalFilename>
                                    </versionInfo>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <!-- dependencies -->
    <dependencies>
        <!-- RyCON base from artifact rycon -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>rycon-main</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- SWT for Windows (32-bit) -->
        <dependency>
            <groupId>org.eclipse.swt</groupId>
            <artifactId>org.eclipse.swt.win32.win32.x86</artifactId>
            <version>4.6.1</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by lukaszlenart** [comment]
`txtFileVersion` is too long
