### ISSUE TITLE
Launch4j 1.7.20 and 1.7.21 not working in Linux

### ISSUE THREAD

**Issue by josemariasoladuran** [lukaszlenart/launch4j-maven-plugin#76]
Launch4j. 

- Affected versions: 1.7.20 and 1.7.21

When execute 'mvn clean package' in Linux the plugin not working and return the next error: 

```
[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.20:launch4j (l4j-clui) on project mdone-desktop-restapi: Failed to build the executable; please verify your configuration. net.sf.launch4j.ExecException: Exec failed (1): /var/quark/repositories/maven-local-repo/net/sf/launch4j/launch4j/3.11/launch4j-3.11-workdir-linux64/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j8001914154679544192rc /tmp/launch4j6268102729254645732o -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.20:launch4j (l4j-clui) on project mdone-desktop-restapi: Failed to build the executable; please verify your configuration.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to build the executable; please verify your configuration.
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:406)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): /var/quark/repositories/maven-local-repo/net/sf/launch4j/launch4j/3.11/launch4j-3.11-workdir-linux64/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j8001914154679544192rc /tmp/launch4j6268102729254645732o
	at net.sf.launch4j.Builder.build(Builder.java:149)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:403)
	... 21 more
Caused by: net.sf.launch4j.ExecException: Exec failed (1): /var/quark/repositories/maven-local-repo/net/sf/launch4j/launch4j/3.11/launch4j-3.11-workdir-linux64/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j8001914154679544192rc /tmp/launch4j6268102729254645732o
	at net.sf.launch4j.Util.exec(Util.java:156)
	at net.sf.launch4j.Cmd.exec(Builder.java:215)
	at net.sf.launch4j.Builder.build(Builder.java:100)
	... 22 more
```

**Comment by lukaszlenart** [comment]
Did you install all the required libs?
https://github.com/lukaszlenart/launch4j-maven-plugin#faq

**Comment by josemariasoladuran** [comment]
No, the version 1.7.19 working perfectly! If the 1.7.21 is a bug version, I think that should be working, no?

**Comment by lukaszlenart** [comment]
Did you notice this https://github.com/lukaszlenart/launch4j-maven-plugin/pull/59 ? It was introduced in 1.7.20
