### ISSUE TITLE
The parameters 'headerType', 'jre' for goal com.akathist.ma ven.plugins.launch4j:launch4j-maven-plugin:1.5.1:launch4j are missing or invalid

### ISSUE THREAD

**Issue by kurtseebauer** [lukaszlenart/launch4j-maven-plugin#9]
I'm getting the error

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.akathist.maven.plugins.launch4j:launc
h4j-maven-plugin:1.5.2:launch4j (default-cli) on project xxx: The parameters 'headerType', 'jre' for goal com
.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.5.1:launch4j are missing or invalid
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:220)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'headerType', 'jre' for goal com.akathist.ma
ven.plugins.launch4j:launch4j-maven-plugin:1.5.2:launch4j are missing or invalid
```

with Version 1.5.2 of the Plugin

``` xml
    <dependency>
            <groupId>com.akathist.maven.plugins.launch4j</groupId>
            <artifactId>launch4j-maven-plugin</artifactId>
            <version>1.5.2</version>
        </dependency>
```

but those parameters are present in the config:

``` xml
    <plugin>
                    <groupId>com.akathist.maven.plugins.launch4j</groupId>
                    <artifactId>launch4j-maven-plugin</artifactId>
                    <version>1.5.2</version>
                    <executions>
                        <execution>
                            <id>l4j-clui</id>
                            <phase>package</phase>
                            <goals>
                                <goal>launch4j</goal>
                            </goals>
                            <configuration>
                                <headerType>gui</headerType>
                                <jar>some.jar</jar>
                                <outfile>xome.exe</outfile>
                                <downloadUrl>http://java.com/download</downloadUrl>
                                <classPath>
                                    <mainClass>${mainClass}</mainClass>
                                    <cp>.</cp>
                                </classPath>
                                <icon>resources/some.ico</icon>
                                <jre>
                                    <minVersion>1.7.0</minVersion>
                                    <jdkPreference>preferJre</jdkPreference>
                                </jre>
                                <versionInfo>
                                    <fileVersion>1.0.0.0</fileVersion>
                                    <txtFileVersion>${project.version}</txtFileVersion>
                                    <fileDescription>${project.name}</fileDescription>
                                    <copyright>2012 hasCode.com</copyright>
                                    <productVersion>1.0.0.0</productVersion>
                                    <txtProductVersion>1.0.0.0</txtProductVersion>
                                    <productName>${project.name}</productName>
                                    <companyName>xxx.eu</companyName>
                                    <internalName>some</internalName>
                                    <originalFilename>some.exe</originalFilename>
                                </versionInfo>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
```

Windows 8.1, current m2e eclipse plugin.
Do you have any ideas? is this a known bug?

**Comment by egrs** [comment]
BTW, have the same issue right now.

**Comment by lukaszlenart** [comment]
@egrs more details please :)

**Comment by kurtseebauer** [comment]
seems like the error message simply indicates that one of the parameters is wrong, pretty misleading. In one case i got it because the icon was not found at the expected location.
